### PR TITLE
scriptdata bad testcase

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by untitaker** [comment]
seems that lychee handles those cases by excluding the script tag from scraping, but that's actually a bug in html5gum. the contents of script tags shouldn't be interpreted as HTML at all.

https://github.com/lycheeverse/lychee/blob/eff77d634283610dbdd481db2d9b1d1162cdea84/lychee-lib/src/extract/html/mod.rs#L44

cc @mre

**Comment by untitaker** [comment]
https://github.com/untitaker/html5gum/pull/98

**Comment by mre** [comment]
Thanks for the info. Could you remind me once this is merged or maybe even update the code in lychee? 🙃

**Comment by untitaker** [comment]
sure

**Comment by untitaker** [comment]
html5gum 0.6.1 is out, and can be bumped in lychee. I guess dependabot will do it, there shouldn't be any code changes required. You may want to check out [CallbackEmitter](https://github.com/untitaker/hyperlink/pull/180) if you want to simplify some code, though it has a bit of overhead (still way faster than most other things)

For some reason it's not possible to hit this bug in lychee. I don't know why, but the code I linked earlier is not related. I guess it doesn't matter.

**Comment by mre** [comment]
Cool. Let's wait until the update comes through, then. 👍

**Pull request merged**
